### ISSUE TITLE
FactorialPoorMans is Wrong while calculate 100000！

### ISSUE THREAD

**Issue by dralausky** [PeterLuschny/Fast-Factorial-Functions#4]
using FactorialPoorMans  100000! = 62539229893133225292127743450985947610617360022758869260132644122553586361071401715089915350807644119201613124308334375194919266695602771631234575383157544214459039923843............while use python math.factorial(100000)  result is 
28242294079603478742934215780245355184774949260912248505789180865429779509010630178725517714138311636107136117373619629514749961831239180227260734090938324220055569688667840380377379444961268380147875111966906386044926144538111370090160766866405407170565952261298041958356778909047541512871140836924251535293096260672271038744246088635454363982931747761.....................

**Comment by PeterLuschny** [comment]
The source code of 'FactorialPoorMans' says: "Good enough to compute the factorial up to n=10000 in a few seconds." It would have been better if I had only written: "Good enough to compute the factorial up to n=10000." 

In other words, it was never intended for larger values, certainly not for n=100000, although I guess that it will work up to n = 2^15 = 32768, but I have not checked this.

After all it's the Poor Man's Factorial and a poor man does not have to deal with real big numbers. It is a fun implementation to play with; remarkable enough what it accomplishes if you realize that shuffling the digits is more text-processing than math! I'm sorry that I didn't make this difference to the other, 'serious' algorithms clear enough.

In any case, thanks for the notice! And if you have a correction that also works for larger values than 2^15 please send me a pull request.
