### ISSUE TITLE
Binomial bug

### ISSUE THREAD

**Issue by nathanhack** [PeterLuschny/Fast-Factorial-Functions#7]
https://github.com/PeterLuschny/Fast-Factorial-Functions/blob/bc6b7a6f1c66819633e347f84026bf6e4bf1e4d7/GoFactorial/primes/primes.go#L40

There seems to be a bug here, if changed to ```< 965``` it alleviates the issue. 

The bug can be exercised by calling ```Binomial(965,3)```

**Comment by PeterLuschny** [comment]
Nathan, I currently have no way of verifying the Go implementation. Please do me a favor and check again, including other values that are close by, and then send me a pull request. I will then merge it.
Thank you!

**Comment by nathanhack** [comment]
Below was the code I ran in the first place that led to me finding the issue.
With the change it does not fail.  I'll try and get a PR in, however, it will likely be next weekend.
```
func Test_binomial(t *testing.T) {
	for n := 10; n < 1<<10; n++ {
		for k := 0; k < n; k++ {
			expected := new(big.Int).Binomial(int64(n), int64(k))
			actual := Binomial(uint64(n), uint64(k))
			if expected.Cmp(actual) != 0 {
				t.Fatalf("expected (%v,%v) to match", n, k)
			}
		}
	}
}
```
